using DarkFantasyMerchant.Core;
using DarkFantasyMerchant.Game;
using NUnit.Framework;
using UnityEditor;

namespace DarkFantasyMerchant.Tests.EditMode
{
    /// <summary>Checks the calendar generated by the world map setup tool.</summary>
    public class CalendarContentTests
    {
        private const string CalendarPath = "Assets/Data/Calendar/Calendar.asset";

        [Test]
        public void Calendar_HasTwelveNamedMonthsAndPositiveValues()
        {
            var calendar = AssetDatabase.LoadAssetAtPath<CalendarDefinition>(CalendarPath);
            Assert.IsNotNull(calendar, CalendarPath);

            Assert.AreEqual(12, calendar.MonthsPerYear);
            Assert.Greater(calendar.DaysPerMonth, 0);
            Assert.AreEqual(7, calendar.DaysPerWeek);
            Assert.Greater(calendar.SecondsPerDay, 0f);
            Assert.Greater(calendar.FastForwardMultiplier, 1f);

            for (int month = 1; month <= calendar.MonthsPerYear; month++)
            {
                // A month without a name falls back to "Mois <n>".
                Assert.IsFalse(calendar.MonthName(month).StartsWith("Mois "), $"month {month} has no name");
            }
        }

        [Test]
        public void Calendar_StartsTheGameOnTheFirstOfJanvis932()
        {
            var calendar = AssetDatabase.LoadAssetAtPath<CalendarDefinition>(CalendarPath);
            Assert.IsNotNull(calendar, CalendarPath);

            GameClock clock = calendar.CreateClock();

            Assert.AreEqual("1 Janvis 932", calendar.Format(clock.Date));
        }
    }
}
