using System.Collections.Generic;
using DarkFantasyMerchant.Game;
using NUnit.Framework;
using UnityEditor;

namespace DarkFantasyMerchant.Tests.EditMode
{
    /// <summary>Checks the economy content generated by the world map setup tool.</summary>
    public class EconomyContentTests
    {
        private const string EconomyPath = "Assets/Data/Economy/Economy.asset";
        private const string MapPath = "Assets/Data/WorldMap/WorldMap.asset";
        private const string ShipPath = "Assets/Data/Ships/MerchantShip.asset";

        private static EconomyDefinition LoadEconomy()
        {
            var economy = AssetDatabase.LoadAssetAtPath<EconomyDefinition>(EconomyPath);
            Assert.IsNotNull(economy, EconomyPath);
            return economy;
        }

        private static WorldMapDefinition LoadMap()
        {
            var map = AssetDatabase.LoadAssetAtPath<WorldMapDefinition>(MapPath);
            Assert.IsNotNull(map, MapPath);
            return map;
        }

        [TestCase(0, "Blé", 10, 2.0)]
        [TestCase(1, "Poisson", 12, 1.5)]
        [TestCase(2, "Bois", 14, 1.0)]
        [TestCase(3, "Bière", 15, 1.5)]
        [TestCase(4, "Sel", 18, 0.5)]
        [TestCase(5, "Laine", 30, 0.5)]
        [TestCase(6, "Cuir", 40, 0.3)]
        [TestCase(7, "Fer", 50, 0.4)]
        [TestCase(8, "Vin", 60, 0.6)]
        [TestCase(9, "Épices", 150, 0.1)]
        public void TheCatalogue_HasTheTenGoods_InOrder(int index, string name, long basePrice, double consumption)
        {
            EconomyDefinition economy = LoadEconomy();

            Assert.AreEqual(10, economy.Goods.Count);
            Assert.AreEqual(name, economy.Goods[index].DisplayName);
            Assert.AreEqual(basePrice, economy.Goods[index].BasePrice);
            Assert.AreEqual(consumption, economy.Goods[index].ConsumptionPerThousand, 1e-9);
        }

        [Test]
        public void TheEconomy_IsUsable()
        {
            EconomyDefinition economy = LoadEconomy();

            Assert.IsTrue(economy.TryValidate(out string problem), problem);
            Assert.DoesNotThrow(() => economy.CreatePricing());
        }

        [Test]
        public void EveryCity_HasInhabitants_AndTwoOrThreeGoodsOfEachProduction()
        {
            EconomyDefinition economy = LoadEconomy();

            foreach (CityDefinition city in LoadMap().Cities)
            {
                Assert.Greater(city.Population, 0, city.name);
                Assert.That(city.EfficientGoods.Count, Is.InRange(2, 3), city.name);
                Assert.That(city.InefficientGoods.Count, Is.InRange(2, 3), city.name);

                var seen = new HashSet<GoodDefinition>();

                foreach (GoodDefinition good in city.EfficientGoods)
                {
                    Assert.GreaterOrEqual(economy.IndexOf(good), 0, city.name);
                    Assert.IsTrue(seen.Add(good), $"{city.name}: {good.name} is listed twice");
                }

                foreach (GoodDefinition good in city.InefficientGoods)
                {
                    Assert.GreaterOrEqual(economy.IndexOf(good), 0, city.name);
                    Assert.IsTrue(seen.Add(good), $"{city.name}: {good.name} is listed twice");
                }

                Assert.DoesNotThrow(() => economy.CreateMarket(city, economy.CreatePricing()), city.name);
            }
        }

        [Test]
        public void EveryGood_IsProducedEfficientlySomewhere()
        {
            var produced = new HashSet<GoodDefinition>();

            foreach (CityDefinition city in LoadMap().Cities)
            {
                produced.UnionWith(city.EfficientGoods);
            }

            foreach (GoodDefinition good in LoadEconomy().Goods)
            {
                Assert.IsTrue(produced.Contains(good), good.name);
            }
        }

        [TestCase("Sparia", 7000)]
        [TestCase("Elforth", 1500)]
        [TestCase("Bactfied", 6000)]
        [TestCase("Hitrun", 1800)]
        [TestCase("Cerbias", 1200)]
        [TestCase("Hazer Empire", 24000)]
        [TestCase("Liveria", 18000)]
        public void ACity_HasItsPopulation(string cityName, int population)
        {
            foreach (CityDefinition city in LoadMap().Cities)
            {
                if (city.DisplayName == cityName)
                {
                    Assert.AreEqual(population, city.Population);
                    return;
                }
            }

            Assert.Fail($"{cityName} is not on the map.");
        }

        [Test]
        public void MerchantShip_HoldsTwoHundredBarrels()
        {
            var ship = AssetDatabase.LoadAssetAtPath<ShipDefinition>(ShipPath);
            Assert.IsNotNull(ship, ShipPath);

            Assert.AreEqual(200, ship.CargoCapacity);
        }
    }
}
