using DarkFantasyMerchant.Game;
using NUnit.Framework;
using UnityEditor;

namespace DarkFantasyMerchant.Tests.EditMode
{
    /// <summary>Checks the expenses generated by the world map setup tool.</summary>
    public class ExpensesContentTests
    {
        private const string ExpensesPath = "Assets/Data/Economy/Expenses.asset";

        [Test]
        public void ASailor_IsPaidTenGoldAWeek()
        {
            var expenses = AssetDatabase.LoadAssetAtPath<ExpensesDefinition>(ExpensesPath);
            Assert.IsNotNull(expenses, ExpensesPath);

            Assert.AreEqual(10, expenses.SailorWeeklyWage);
        }
    }
}
