using DarkFantasyMerchant.Game;
using NUnit.Framework;
using UnityEditor;

namespace DarkFantasyMerchant.Tests.EditMode
{
    /// <summary>Checks the player start generated by the world map setup tool.</summary>
    public class PlayerStartContentTests
    {
        private const string PlayerStartPath = "Assets/Data/Player/PlayerStart.asset";

        [Test]
        public void ThePlayer_StartsWithTenThousandGold()
        {
            var playerStart = AssetDatabase.LoadAssetAtPath<PlayerStartDefinition>(PlayerStartPath);
            Assert.IsNotNull(playerStart, PlayerStartPath);

            Assert.AreEqual(10000, playerStart.CreateTreasury().Gold);
        }

        [Test]
        public void ThePlayerShip_StartsWithTwelveSailors()
        {
            var playerStart = AssetDatabase.LoadAssetAtPath<PlayerStartDefinition>(PlayerStartPath);
            Assert.IsNotNull(playerStart, PlayerStartPath);

            Assert.AreEqual(12, playerStart.StartingCrew);
        }
    }
}
