using DarkFantasyMerchant.Core;
using DarkFantasyMerchant.Game;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace DarkFantasyMerchant.Tests.EditMode
{
    /// <summary>Checks the ship content generated by the world map setup tool.</summary>
    public class ShipContentTests
    {
        private const string DefinitionPath = "Assets/Data/Ships/MerchantShip.asset";
        private const string PrefabPath = "Assets/Prefabs/Ships/Ship.prefab";
        private const string RoutePrefabPath = "Assets/Prefabs/Ships/ShipRoute.prefab";

        [Test]
        public void MerchantShip_HasTheRightSpriteForEveryDirection()
        {
            var definition = AssetDatabase.LoadAssetAtPath<ShipDefinition>(DefinitionPath);
            Assert.IsNotNull(definition, DefinitionPath);

            for (int i = 0; i < ShipDefinition.DirectionCount; i++)
            {
                var direction = (CompassDirection)i;
                Sprite sprite = definition.SpriteFor(direction);

                Assert.IsNotNull(sprite, direction.ToString());
                Assert.AreEqual($"MerchantShip_{direction}", sprite.name);
            }
        }

        [Test]
        public void MerchantShip_HasANameAndAPositiveSpeed()
        {
            var definition = AssetDatabase.LoadAssetAtPath<ShipDefinition>(DefinitionPath);
            Assert.IsNotNull(definition, DefinitionPath);

            Assert.IsNotEmpty(definition.DisplayName);
            Assert.Greater(definition.Speed, 0f);
        }

        [Test]
        public void ShipPrefab_DrawsAboveCityMarkers()
        {
            var prefab = AssetDatabase.LoadAssetAtPath<ShipView>(PrefabPath);
            Assert.IsNotNull(prefab, PrefabPath);

            var spriteRenderer = prefab.GetComponent<SpriteRenderer>();
            Assert.IsNotNull(spriteRenderer);
            Assert.Greater(spriteRenderer.sortingOrder, 10);
            Assert.IsNotNull(spriteRenderer.sprite);
        }

        [Test]
        public void ShipRoutePrefab_DrawsADashedAndASolidLine_BelowCityMarkers()
        {
            var prefab = AssetDatabase.LoadAssetAtPath<ShipRouteView>(RoutePrefabPath);
            Assert.IsNotNull(prefab, RoutePrefabPath);

            LineRenderer[] lines = prefab.GetComponentsInChildren<LineRenderer>(true);
            Assert.AreEqual(2, lines.Length);

            int dashedLines = 0;

            foreach (LineRenderer line in lines)
            {
                Assert.IsNotNull(line.sharedMaterial, line.name);
                Assert.IsTrue(line.useWorldSpace, line.name);
                Assert.That(line.sortingOrder, Is.InRange(1, 9), line.name);

                if (line.textureMode == LineTextureMode.Tile)
                {
                    dashedLines++;
                    Texture dashes = line.sharedMaterial.mainTexture;
                    Assert.IsNotNull(dashes, "the dashed line has no dash texture");
                    Assert.AreEqual(TextureWrapMode.Repeat, dashes.wrapMode);
                }
            }

            Assert.AreEqual(1, dashedLines);

            // Dashes on the remaining line would start at the ship and slide with it.
            var serialized = new SerializedObject(prefab);
            var sailedLine = serialized.FindProperty("sailedLine").objectReferenceValue as LineRenderer;
            var remainingLine = serialized.FindProperty("remainingLine").objectReferenceValue as LineRenderer;
            Assert.IsNotNull(sailedLine, "sailedLine");
            Assert.IsNotNull(remainingLine, "remainingLine");
            Assert.AreEqual(LineTextureMode.Tile, sailedLine.textureMode);
            Assert.AreNotEqual(LineTextureMode.Tile, remainingLine.textureMode);

            var marker = serialized.FindProperty("destinationMarker").objectReferenceValue as SpriteRenderer;
            Assert.IsNotNull(marker);
            Assert.IsNotNull(marker.sprite);
            Assert.That(marker.sortingOrder, Is.InRange(1, 9));
        }
    }
}
