using DarkFantasyMerchant.Core;
using DarkFantasyMerchant.Game;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace DarkFantasyMerchant.Tests.EditMode
{
    /// <summary>Checks the ship content generated by the world map setup tool.</summary>
    public class ShipContentTests
    {
        private const string DefinitionPath = "Assets/Data/Ships/MerchantShip.asset";
        private const string PrefabPath = "Assets/Prefabs/Ships/Ship.prefab";

        [Test]
        public void MerchantShip_HasTheRightSpriteForEveryDirection()
        {
            var definition = AssetDatabase.LoadAssetAtPath<ShipDefinition>(DefinitionPath);
            Assert.IsNotNull(definition, DefinitionPath);

            for (int i = 0; i < ShipDefinition.DirectionCount; i++)
            {
                var direction = (CompassDirection)i;
                Sprite sprite = definition.SpriteFor(direction);

                Assert.IsNotNull(sprite, direction.ToString());
                Assert.AreEqual($"MerchantShip_{direction}", sprite.name);
            }
        }

        [Test]
        public void MerchantShip_HasANameAndAPositiveSpeed()
        {
            var definition = AssetDatabase.LoadAssetAtPath<ShipDefinition>(DefinitionPath);
            Assert.IsNotNull(definition, DefinitionPath);

            Assert.IsNotEmpty(definition.DisplayName);
            Assert.Greater(definition.Speed, 0f);
        }

        [Test]
        public void ShipPrefab_DrawsAboveCityMarkers()
        {
            var prefab = AssetDatabase.LoadAssetAtPath<ShipView>(PrefabPath);
            Assert.IsNotNull(prefab, PrefabPath);

            var spriteRenderer = prefab.GetComponent<SpriteRenderer>();
            Assert.IsNotNull(spriteRenderer);
            Assert.Greater(spriteRenderer.sortingOrder, 10);
            Assert.IsNotNull(spriteRenderer.sprite);
        }
    }
}
